### ISSUE TITLE
Dependency with xcode build requirement causes formula to be skipped

### ISSUE THREAD

**Issue by scpeters** [Homebrew/homebrew-test-bot#115]
The `qt` formula has a [:build requirement on :xcode](https://github.com/Homebrew/homebrew-core/blob/master/Formula/qt.rb#L29), but recently (possibly since #14), I am unable to build a bottle for a formula that depends on `qt` ( https://github.com/osrf/homebrew-simulation/pull/261 ) on a build machine that only has the command-line tools installed. The [build fails](https://build.osrfoundation.org/job/generic-release-homebrew_bottle_builder-sierra/45/console) with the following console message:

~~~
==> SKIPPING: osrf/simulation/ignition-gui
A full installation of Xcode.app is required to compile this software.
Installing just the Command Line Tools is not sufficient.
Xcode can be installed from the App Store.
~~~

It should be fine to build without full Xcode since `qt` is being installed from a bottle. I can try to help with some guidance. I'm not sure if the problem is here or in `brew`.

**Comment by scpeters** [comment]
Maybe some logic from https://github.com/Homebrew/brew/pull/2815 could be added to the test-bot?

**Comment by MikeMcQuaid** [comment]
@scpeters Can you fill out the issue template, please?

**Comment by scpeters** [comment]
I didn't see a template when I clicked on new issue.

**Comment by scpeters** [comment]
I could file in a different repo that has issue templates if you prefer.

**Comment by MikeMcQuaid** [comment]
Apologies, I misread this @scpeters. https://github.com/Homebrew/homebrew-test-bot/blob/80333911e7130b9542a6fe2b94c1311b52cef319/cmd/brew-test-bot.rb#L554-L578 is the relevant code; I agree that this code could be adjusted to handle built-time requirements for bottles.

**Comment by scpeters** [comment]
No problem; I'll take a look at that code and work on a PR.

**Comment by scpeters** [comment]
I thought https://github.com/Homebrew/brew/pull/3479 would fix this, but it didn't. I still need to make another attempt at #116.

**Comment by MikeMcQuaid** [comment]
@scpeters Can you still reproduce this?

**Comment by scpeters** [comment]
Yeah, I'm still using my branch from #116 when necessary, most recently for https://github.com/osrf/homebrew-simulation/pull/371. I've tried a couple times to follow @ilovezfs's recommendation in https://github.com/Homebrew/homebrew-test-bot/pull/116#issuecomment-324595473 but I don't understand the code well enough.

**Comment by scpeters** [comment]
It's confusing to me because in my testing, I see the missing requirement complaint arise from the `recursive_requirements` function in `software_spec`, but @ilovezfs recommended modifying `recursive_dependencies`.

**Comment by ilovezfs** [comment]
You might need to modify both. Requirements of dependencies are requirements.

**Comment by ilovezfs** [comment]
@scpeters https://github.com/Homebrew/brew/blob/master/Library/Homebrew/requirement.rb#L194

**Comment by ilovezfs** [comment]
@scpeters  I don't see a good way to do this without passing a block into recursive_requirements to filter out the build-time requirements of the bottled dependencies just as formula_installer does. If you still think https://github.com/Homebrew/homebrew-test-bot/pull/116 works as expected, we should try that, if you want to reopen it.

**Comment by scpeters** [comment]
@ilovezfs thanks for taking another look at this!
