### ISSUE TITLE
`brew test-bot` indicating action success when a formula fails to build

### ISSUE THREAD

**Issue by mister-walter** [Homebrew/homebrew-test-bot#1178]
I use the Homebrew test-bot functionality to support a tap, [acl2s/homebrew-acl2s](https://github.com/acl2s/homebrew-acl2s). I noticed that the `brew test-bot --only-formulae` command does not cause GitHub Actions to report a failure when a formula fails to install. An example of this can be seen [in this GitHub Action run](https://github.com/acl2s/homebrew-acl2s/actions/runs/10480217167/job/29027403026#step:8:22). The step has failed and an appropriate error annotation has been created, but the `brew test-bot` command exits with a non-error status code so GitHub Actions considers the step to have completed successfully.

I believe this behavior occurs because the test bot will ignore failed formulae tests under most conditions (see [line 406 in lib/tests/formulae.rb](https://github.com/Homebrew/homebrew-test-bot/blob/f8d4b0d42e84c43a750125c3a5fcc43ae569218f/lib/tests/formulae.rb#L406)). From my reading of that conditional, failed formulae tests are not skipped only if the `--test-default-formula` flag is provided, the failed formula has a bottle available compatible with the system running the tests, or if it is a newly added formula (since the last commit, according to the test-bot's auto detection or the `--added-formulae` flag). These conditions seem to be quite strict, so I'd love a command-line flag that allows me to enforce that no failed formulae tests are skipped. I'm happy to submit a PR if such a flag would be considered reasonable.

Note that #910 appears to reference this behavior, and #791 appears to indicate this behavior is expected if no bottle exists for the formula under test.

**Comment by Bo98** [comment]
This is in part, or at least the Linux failure is, caused by you deleting the `bottle` block. If you are using `brew pr-pull` then you don't need to delete the bottle block as that should update it.

Though that does raise a different point that we probably shouldn't downgrade to errors if `Formula#bottle_defined?` is false.

**Comment by mister-walter** [comment]
Thanks very much for that info! I'm not sure why I thought it was necessary to delete the bottle block, I'll avoid doing that in the future.

It would have been helpful for me if this behavior was documented somewhere (maybe it is and I missed it?). It is surprising to me that whether or not a bottle already exists for the formula is relevant to the testing, unless I'm really misunderstanding what's going on here and the testing is intended to check whether an existing bottle installs without error rather than that the formula builds without error.

**Comment by MikeMcQuaid** [comment]
> It would have been helpful for me if this behavior was documented somewhere (maybe it is and I missed it?).

This `brew test-bot` tool is primarily built for Homebrew's own use and is too complicated to document all these types of edge-case behaviours, sorry (and, if we did document it, the documentation would likely get outdated very quickly).

Will review a PR to improve the behaviour here.

**Comment by MikeMcQuaid** [comment]
Reopening because @carlocab has picked this up ❤️
