### ISSUE TITLE
Bottle build fails with env filtering if GIT_COMMITTER_IDENT can't be found

### ISSUE THREAD

**Issue by scpeters** [Homebrew/homebrew-test-bot#131]
The first bottle builds that we have tried since environment filtering was enabled in #129 have been [failing on all our build machines](https://build.osrfoundation.org/view/os_homebrew/job/generic-release-homebrew_bottle_builder-sierra/98/) with the following error:

~~~
==> brew pull --clean https://github.com/osrf/homebrew-simulation/pull/312
==> FAILED
==> Fetching patch 
Patch: https://github.com/osrf/homebrew-simulation/pull/312.patch
==> Applying patch

*** Please tell me who you are.

Run

  git config --global user.email "you@example.com"
  git config --global user.name "Your Name"

to set your account's default identity.
Omit --global to set the identity only in this repository.

fatal: unable to auto-detect email address (got 'jenkins@t1000.(none)')

*** Please tell me who you are.

Run

  git config --global user.email "you@example.com"
  git config --global user.name "Your Name"

to set your account's default identity.
Omit --global to set the identity only in this repository.

fatal: unable to auto-detect email address (got 'jenkins@t1000.(none)')
Error: Patch failed to apply: aborted.
~~~

I traced this error to the invocation of [git am in brew pull](https://github.com/Homebrew/brew/blob/master/Library/Homebrew/dev-cmd/pull.rb#L344) and then discovered that `git am` [wants a valid committer identity](https://github.com/git/git/blob/v2.15.0/builtin/am.c#L2319-L2320) (including email). The build machines have a `~/.gitconfig` with name and email, and I also set the `GIT_COMMITTER_EMAIL` before invoking `test-bot`, but environment filtering wipes those out. Note that a direct way to test the committer identity is with `git var GIT_COMMITTER_IDENT`.

This is where it gets weird. When an email isn't provided, `git` tries to construct one from the username and hostname, but it [declares the hostname invalid](https://github.com/git/git/blob/v2.15.0/ident.c#L94-L136) if it doesn't contain any `.` characters. That seems weird to me since many of our machines don't have `.` characters in their hostnames. I was able to workaround the issue by appending `.local` to the hostnames of these machines, but it seems like that shouldn't be necessary.

I'm guessing that `git am` wants the committer identity in case `--signoff` is passed, but I don't think it needs to check it in every case. This could be a `git` bug, but it exists in all the released versions of git, so it would be nice to have a workaround that doesn't require changing build machine hostnames.

**Comment by ilovezfs** [comment]
https://github.com/Homebrew/homebrew-test-bot/commit/7dbae6cc7b1c6d071c993b8cef6b7058961ee187

did you try passing --git-name and --git-email ?

**Comment by scpeters** [comment]
Yeah, I tried that:

* https://bitbucket.org/osrf/release-tools/commits/10ed6556de576dd0f5d4df07cf7329722a31fcdb
* https://build.osrfoundation.org/view/os_homebrew/job/generic-release-homebrew_bottle_builder-sierra/105/console

but the key variable git is looking for is `GIT_COMMITTER_EMAIL`, which is no longer set by that the `--git-email` param after that commit, and it gets filtered out anyway by [brew](https://github.com/Homebrew/brew/blob/master/bin/brew#L68) when `brew pull` is called

**Comment by scpeters** [comment]
Potential fix in https://github.com/scpeters/brew/commit/ba175a54a947eb95d812d5385040f50caf36bc4b

Pull request forthcoming

**Comment by scpeters** [comment]
fixed by https://github.com/Homebrew/brew/pull/3489

thanks @MikeMcQuaid !
