### ISSUE TITLE
Travis macOS job failure when triggered by a commit to an non-master branch

### ISSUE THREAD

**Issue by tommyang** [Homebrew/homebrew-test-bot#182]
I encountered this while trying to set up Travis CI for a tap. [Travis job log](https://travis-ci.com/tommyang/homebrew-gerbera/jobs/145252683)

I have only seen this failure happen if the Travis CI build is triggered by a commit to an non-master branch, not by PRs. Did not test if the same will happen if commits directly to master. 

Looks like it is not isolated. Similar failures occur in [denji/homebrew-nginx's log](https://travis-ci.org/denji/homebrew-nginx/jobs/411553589) & [dunn/homebrew-emacs's log](https://travis-ci.org/dunn/homebrew-emacs/jobs/383218369). (Note that these two repos' builds also contains an Linuxbrew job that does not fail. )

The only "Error:" message that is unique to the macOS jobs is:
`Error: File name too long @ dir_s_mkdir - /Users/travis/build/tommyang/homebrew-gerbera/brewbot/` (might need to click the raw log button to see, somehow hidden by Travis)

**Comment by MikeMcQuaid** [comment]
@tommyang Could you try to submit a pull request? We're unlikely to work on fixing this ourselves as we're currently investigating non-Travis CI solutions and Travis is working fine for us.

**Comment by tommyang** [comment]
I would love to submit a PR. However, I was not (and still isn't) sure about the root cause. 

I just did a "bisect" using the log of dunn/homebrew-emacs and found that one such commit [builds successfully](https://travis-ci.org/dunn/homebrew-emacs/jobs/375171698) on May 4th while another such commit [fails this way](https://travis-ci.org/dunn/homebrew-emacs/jobs/376020490) on May 7th. 

During this timeframe, the only change to test-bot is #155. I can't make sense of why this change would result in the error message above. 

Tagging @dunn in case they have additional insight.

**Comment by dunn** [comment]
I see that error intermittently, but I've never tracked down the cause of it.

**Comment by MikeMcQuaid** [comment]
Ok, this doesn't seem actionable as-is but we'll consider a PR. Thanks!
