### ISSUE TITLE
Test-bot failed with "stable version should not decrease"

### ISSUE THREAD

**Issue by twlz0ne** [Homebrew/homebrew-test-bot#197]
I have a [fomula](https://github.com/twlz0ne/homebrew-ccls/blob/master/Formula/ccls.rb) like this:

```ruby
  if MacOS.version <= :el_capitan
    url "https://github.com/MaskRay/ccls.git",
        :tag => "0.20180812",
        :revision => "06aa25233567ae16a58a6f5237aacfd9e02aa29d"
  else
    url "https://github.com/MaskRay/ccls.git",
        :tag => "0.20180913",
        :revision => "56c6ec43dfd87ed2e44418b8d172307d87327a64"
  end
```

And then build each version with independent image:

```yaml
matrix:
  include:
    - env: OSX=10.11
      compiler: clang
      osx_image: xcode8
    - env: OSX=10.12
      compiler: clang
      osx_image: xcode9.2
```

So far, everything is going well, all build jobs passed:

![build__39_-_twlz0ne_homebrew-ccls_-_travis_ci](https://user-images.githubusercontent.com/2653486/46332726-35607f80-c650-11e8-9284-4521b2e0f2b1.png)

But after increasing the reversion from `0.20180913` to `0.20180924` for osx 10.12:

```diff
  if MacOS.version <= :el_capitan
    url "https://github.com/MaskRay/ccls.git",
        :tag => "0.20180812",
        :revision => "06aa25233567ae16a58a6f5237aacfd9e02aa29d"
  else
    url "https://github.com/MaskRay/ccls.git",
-       :tag => "0.20180913",
+       :tag => "0.20180924",
-       :revision => "56c6ec43dfd87ed2e44418b8d172307d87327a64"
+       :revision => "41fcc0272c8c93fcbe52f24ef587e633a9dcc7e1"
  end
```

I've got failure from job([OSX=10.11](https://travis-ci.com/twlz0ne/homebrew-ccls/jobs/149097657)):

```log
$ export OSX=10.11
...
$ if [ "$OSX" == "10.12" ]; then brew test-bot --skip-setup; else brew test-bot; fi
...
==> brew audit twlz0ne/ccls/ccls --online
...
Error: 1 problem in 1 formula detected
twlz0ne/ccls/ccls:
  * stable version should not decrease (from 0.20180913 to 0.20180812)
==> FAILED
```

I didn't change the reversion for osx 10.11, why prompting these? Seems the reversions are missed up.

And at the same time, the job([OSX=10.12](https://travis-ci.com/twlz0ne/homebrew-ccls/jobs/149097658)) passed.

**Comment by MikeMcQuaid** [comment]
We don't support different versions per-OS in `test-bot`. We'll review a PR to fix this either here or in Homebrew/brew.
