### ISSUE TITLE
Question - How does Jenkins know which formula to bottle?

### ISSUE THREAD

**Issue by ladislas** [Homebrew/homebrew-test-bot#251]
Hi there! 

Following on my quest to automatize the process of building and publishing bottles for taps, I've spent quite some time studying Jenkins' console outputs and the `brew-test-bot.rb` source code.

One thing I can't get my head around is this:

> How does Jenkins know which formula to bottle?

If we take for example https://github.com/Homebrew/homebrew-core/pull/39211, the corresponding logs are:

- general log: https://jenkins.brew.sh/job/Homebrew%20Core%20Pull%20Requests/41069/console
- high sierra log: https://jenkins.brew.sh/job/Homebrew%20Core%20Pull%20Requests/41069/version=high_sierra/console

In the High Sierra log, one can find this line...

```
brew pull --clean https://github.com/Homebrew/homebrew-core/pull/39211
```

...where the pull url comes from the `ghprbPullLink` variable.
And then it magically seems to know which formula to test and bottle (`qbs`)!

```
brew uses --recursive qbs
```

How could I reproduce the same behavior in Azure Pipelines? 

For the moment I'm passing the formula name as a parameter to `brew test-bot` but what if I have multiple formulae?

Thanks a lot for your help!

Best,  
-- Ladislas

**Comment by sjackman** [comment]
Here's the magic line:
https://github.com/Homebrew/homebrew-test-bot/blob/fa91172273887efb8aa799a3401cced7690cbf0f/cmd/brew-test-bot.rb#L556-L557

**Comment by ladislas** [comment]
Thanks @sjackman! That was my guess :)

So doest that mean I have to pass `--tap=username/repo` when calling `brew test-bot` to bottle tap's formulae in Azure?

**Comment by MikeMcQuaid** [comment]
@ladislas You shouldn't need to, no. I'm glad you're working on this as we plan to (eventually) use Azure Pipelines to bottle some/all Homebrew/homebrew-core formulae.

**Comment by MikeMcQuaid** [comment]
@ladislas Closing this as the question is answered. In general can you use Discourse for questions? Feel free to mention me by username there and I'll reply quicker. Thanks again!

**Comment by ladislas** [comment]
> In general can you use Discourse for questions? 

Sure! Will do!
