### ISSUE TITLE
Bottles can't be found when building multiple bottles with common indirect dependents

### ISSUE THREAD

**Issue by scpeters** [Homebrew/homebrew-test-bot#266]
In https://github.com/Homebrew/homebrew-core/pull/39225, both `python` and `python@2` are updated to use a new version of `setuptools`. `python` gets built first and all its dependencies are tested without any failures. Then it is uninstalled, the `python@2` bottle is built (successfully), and the dependencies of `python@2` are tested. The first formula to fail is `alot`, which depends directly on `python@2`, but not directly on `python`:

* https://github.com/Homebrew/homebrew-core/blob/master/Formula/alot.rb#L18-L25

`alot` has multiple direct dependencies that depend indirectly on `python`, such as `gpgme` and `notmuch`. For some reason, `test-bot` ends up trying to find the new python bottle on bintray instead of installing the recently built and unpublished one from the filesystem.

~~~
==> Installing alot dependency: python
==> Downloading https://homebrew.bintray.com/bottles/python-3.7.3.mojave.bottle.1.tar.gz
curl: (22) The requested URL returned error: 404 Not Found
Error: Failed to download resource "python"
Download failed: https://homebrew.bintray.com/bottles/python-3.7.3.mojave.bottle.1.tar.gz
~~~

Note that `alot` was also tested successfully when `python`'s dependencies were tested, but failed later when `python@2` dependencies were tested.

I think a workaround is to split up changes into separate pull requests, though this may not always be feasible or desired. I have observed this issue at times while maintaining the osrf/simulation tap, but I haven't reported it until now because I've found it difficult to describe succinctly with core formulae. I've observed it when building multiple bottles in a pull request and some downstream formulae depend on one of the formula directly, and the other indirectly.

I've saved the failed jenkins build log from https://jenkins.brew.sh/job/Homebrew%20Core%20Pull%20Requests/43640/version=mojave/ in the following gist:

* https://gist.github.com/scpeters/7beb8914c63b766849106a95f4ddc7c3

**Comment by MikeMcQuaid** [comment]
Thanks for the write-up @scpeters. The problem here is likely that `python` is being installed when it shouldn't be.

**Comment by MikeMcQuaid** [comment]
@scpeters Can you figure out which `brew test-bot` uninstall line is removing it incorrectly? I had a glance through them all and there were none I could see that seemed to be the culprit.

**Comment by scpeters** [comment]
At the end of `def formula(formula_name)` (which builds a bottle for the named formula and tests all its dependents), the following lines uninstall the recently bottled formula `unless @all_formulae_dependencies.include?(formula_name)`:

https://github.com/Homebrew/homebrew-test-bot/blob/master/cmd/brew-test-bot.rb#L1015-L1017

The `@all_formulae_dependencies` variable is populated in `def formulae` before building any bottles. In the case of Homebrew/homebrew-core#39225, the named formulae are `python` and `python@2` and I added some print statements to see their dependencies, as well as the contents of `@all_formulae_dependencies`:

~~~
python dependencies: ["gdbm", "openssl", "pkg-config", "readline", "sqlite", "xz"]
python@2 dependencies: ["gdbm", "openssl", "pkg-config", "readline", "sqlite"]
@all_formulae_dependencies: ["gdbm", "openssl", "pkg-config", "readline", "sqlite", "xz", "gdbm", "openssl", "pkg-config", "readline", "sqlite"]
~~~

`python` is tested first, and since it is not a dependency of `python@2`, it is uninstalled at the end of `formula("python")`. The `python@2` bottle then builds successfully, but when testing the dependents of `python@2` with `install_bottled_dependent(dependent)`, some of those dependents also depend on `python`, and `install_bottled_dependent` doesn't have any special logic to try to install any of the `@formulae` that have been already been bottled but also uninstalled.

So I can think of three approaches for a fix:

1. Don't uninstall something like `python` if it will be needed by any dependents of other formulae. This could potentially increase chances for opportunistic linking.

2. Be smarter about installing recently bottled but uninstalled `@formulae` in `install_bottled_dependent`.

3. (Bad) Skip testing dependents that depend on recently bottled but uninstalled `@formulae`. This just papers over the problem by testing fewer things. I don't recommend it.

**Comment by MikeMcQuaid** [comment]
Thanks again @scpeters! Should be fixed by https://github.com/Homebrew/homebrew-test-bot/pull/267, let me know what you think and (ideally) test it out.
