### ISSUE TITLE
brew test-bot does not make azure pipelines fail for reverse dependencies

### ISSUE THREAD

**Issue by iMichka** [Homebrew/homebrew-test-bot#273]
This build is green: https://github.com/Homebrew/linuxbrew-core/pull/14737
But we had a bunch of failures in the logs: https://dev.azure.com/Homebrew/56a87eb4-3180-495a-9117-5ed6c79da737/_apis/build/builds/17317/logs/16

It looks like circle.ci and jenkins where looking for the "FAILED" string in uppercase (to be confirmed?). Azure does not do that.

@sjackman @MikeMcQuaid maybe you have a quick idea on what is going on here? If not I'll dig through the code. It looks like we already have something in place in the run function, with a failure check: https://github.com/Homebrew/homebrew-test-bot/blob/master/cmd/brew-test-bot.rb#L1345-L1362. But maybe the exit code is not correctly propagated ...

**Comment by MikeMcQuaid** [comment]
You need to do `set -e` in multiline Bash steps (i.e. those with `- bash: |`) or it won't respect the exit code.

**Comment by iMichka** [comment]
Thanks !
