### ISSUE TITLE
Option to exit successfully if no bottles are found for upload

### ISSUE THREAD

**Issue by dawidd6** [Homebrew/homebrew-test-bot#281]
I think it would be nice to have an option like `--exit-if-no-bottles`. When passed, `test-bot` would just call `exit` for example if no bottles were found for uploading.

Relevant line of code: https://github.com/Homebrew/homebrew-test-bot/blob/bb48704eb882c0c7867d6ec275ab22bca2c60db9/cmd/brew-test-bot.rb#L1406

Possible patch:
```diff
diff --git a/cmd/brew-test-bot.rb b/cmd/brew-test-bot.rb
index f436505..b91a109 100755
--- a/cmd/brew-test-bot.rb
+++ b/cmd/brew-test-bot.rb
@@ -1403,7 +1403,17 @@ module Homebrew
 
     copy_bottles_from_jenkins unless ENV["JENKINS_HOME"].nil?
 
-    raise "No bottles found in #{Dir.pwd}!" if Dir["*.bottle*.*"].empty? && !ARGV.include?("--dry-run")
+    if Dir["*.bottle*.*"].empty?
+      message = "No bottles found in #{Dir.pwd}!"
+      unless ARGV.include?("--dry-run")
+        if ARGV.include?("--exit-if-no-bottles")
+          puts message
+          exit
+        else
+          raise message
+        end
+      end
+    end
 
     json_files = Dir.glob("*.bottle.json")
     bottles_hash = json_files.reduce({}) do |hash, json_file|

```

**Comment by MikeMcQuaid** [comment]
What would be the purpose of running the upload step if there's no bottles there to upload?

**Comment by dawidd6** [comment]
IIRC `test-bot` will just exit if no formulas were changed between commits.
If one for example has a script that first executes `test-bot` and then `test-bot --ci-upload`, it will fail when attempting to upload, because no bottles were built, beacuse no changes to any formula were detected.

Might be an edge case, but I'm currently workarounding this in my CI jobs by performing the same check like in the code above, before executing `test-bot --ci-upload`.

**Comment by dawidd6** [comment]
Okay that was a bad idea. Didn't think about this through enough.

**Comment by MikeMcQuaid** [comment]
Not a bad idea, a good question!
