### ISSUE TITLE
Can't have other branch than master while uploading

### ISSUE THREAD

**Issue by dawidd6** [Homebrew/homebrew-test-bot#302]
Using Github Actions, if one runs `brew test-bot --ci-upload`, the tap is automatically resetted to `master`. Which is undesirable in situations when one checkouts the repo (tap) manually to, let's say, another branch, before uploading the bottles. This is of course not a problem for taps, that rely on `test-bot` for pushing tags, but it is broken for the ones that push branches for example.

Interesting lines of code:
https://github.com/Homebrew/homebrew-test-bot/blob/af6fcf3ef7118acd72e2eb94a9b49b45e8433d67/lib/test_bot.rb#L161-L178

What I'm talking about is demonstrated here: https://github.com/dawidd6/homebrew-tap/pull/71/checks?check_run_id=329233117#step:8:1

I didn't encounter this issue before, cause I didn't try to add a new formula and build a bottle for it via PR.

**Comment by MikeMcQuaid** [comment]
> Which is undesirable in situations when one checkouts the repo (tap) manually to, let's say, another branch, before uploading the bottles.

Can you elaborate why you'd want/need to do this?

**Comment by dawidd6** [comment]
The core reason is that if one of those env variables are not set:
```ruby
 pr = ENV["UPSTREAM_PULL_REQUEST"] || 
     ENV["CHANGE_ID"] || 
     ENV["CIRCLE_PR_NUMBER"] 
```

the required `brew pull` step will not execute and if one for example already has the tap checked out to PR head branch, it will still be resetted to `master`:
```
safe_system "git", "checkout", "-f", "master" 
```

of course, one those env variables could be set, but then the `git tag` and `git push` steps will be executed and I don't want that.

Now that I'm thinking about it, the best solution would be to provide a new option: `--no-push`. Using this option, I would be able to set for example `CHANGE_ID` and `test-bot` would then execute `brew pull`, but won't `git tag` and `git push`. Then I could easily push the new `pr-` branch with bottle commit as usual.

**Comment by MikeMcQuaid** [comment]
@dawidd6 How about moving all that logic into `if pr`?

**Comment by dawidd6** [comment]
Yes, that might actually help. Will do the PR.

**Comment by dawidd6** [comment]
Thanks for merging the PR! It works now.
