### ISSUE TITLE
git prune etc. should be performed under --ci-upload

### ISSUE THREAD

**Issue by Bo98** [Homebrew/homebrew-test-bot#304]
homebrew-test-bot has code to perform prune, gc, clean etc. on the Git repository, called from here:

https://github.com/Homebrew/homebrew-test-bot/blob/af6fcf3ef7118acd72e2eb94a9b49b45e8433d67/lib/test.rb#L836-L838

This code however does not run when `--ci-upload` is used.

It perhaps should be since the Homebrew Bottle job is asking for it:

```
==> Fetching /var/lib/jenkins/workspace/Homebrew Bottles/Library/Taps/homebrew/homebrew-core...
Auto packing the repository in background for optimum performance.
See "git help gc" for manual housekeeping.
error: The last gc run reported the following. Please correct the root cause
and remove .git/gc.log.
Automatic cleanup will not be performed until the file is removed.

warning: There are too many unreachable loose objects; run 'git prune' to remove them.
```

**Comment by MikeMcQuaid** [comment]
The "fetching" here is from the Jenkins configuration so have added `find . -name .git/gc.log -delete` in there which should ensure the automated prune will be run. Thanks for the issue 👍

**Comment by Bo98** [comment]
Sorry - I perhaps confusingly raised this at the same time as the issues today. This is specifically about the Homebrew Bottle job and not Pull Requests, so the fetching is done by `brew update-reset`:

```
+ brew update-reset
==> Fetching /var/lib/jenkins/workspace/Homebrew Bottles...

==> Resetting /var/lib/jenkins/workspace/Homebrew Bottles...
Reset branch 'master'
Branch master set up to track remote branch master from origin.
Your branch is up-to-date with 'origin/master'.

==> Fetching /var/lib/jenkins/workspace/Homebrew Bottles/Library/Taps/homebrew/homebrew-core...
Auto packing the repository in background for optimum performance.
See "git help gc" for manual housekeeping.
error: The last gc run reported the following. Please correct the root cause
and remove .git/gc.log.
Automatic cleanup will not be performed until the file is removed.

warning: There are too many unreachable loose objects; run 'git prune' to remove them.
```

Indeed that line is good to add anyway, since that will benefit Pull Requests which use the Git plugin alone and thus fix the bigger issues today. Though it won't help Homebrew Bottles which is screaming for a `git prune`.

**Comment by MikeMcQuaid** [comment]
> Though it won't help Homebrew Bottles which is screaming for a `git prune` rather than just a `gc`.

I've nuked the directory entirely so it will be recloned.
