### ISSUE TITLE
Test bot fails when brew git is tested

### ISSUE THREAD

**Issue by Bo98** [Homebrew/homebrew-test-bot#330]
We've been merging failing `git` builds for far too long - ideally we wouldn't be merging anything that's red. [Here is an example failure from git](https://jenkins.brew.sh/job/Homebrew%20Core%20Pull%20Requests/57713/version=mojave/console) - please ignore the `brew test` failure here as that is something specific to that version bump. I'm talking about this at the end:

```
==> brew uninstall --force gettext pcre2

==> git -C homebrew/homebrew-core checkout master -f
==> FAILED
dyld: Library not loaded: /usr/local/opt/pcre2/lib/libpcre2-8.0.dylib
  Referenced from: /usr/local/bin/git
  Reason: image not found
dyld: Library not loaded: /usr/local/opt/pcre2/lib/libpcre2-8.0.dylib
  Referenced from: /usr/local/bin/git
  Reason: image not found

==> git -C homebrew/homebrew-core reset --hard origin/master
==> FAILED
dyld: Library not loaded: /usr/local/opt/pcre2/lib/libpcre2-8.0.dylib
  Referenced from: /usr/local/bin/git
  Reason: image not found
```

homebrew-test-bot uses whatever git is in the path (or Xcode.app if there's nothing). At the point of failure above, brew git is installed but non-functional because `pcre2` is uninstalled. This uninstall is intentional as if there is subsequent formulae being built then we want a cleaner environment, and to also make better use of disk space. The `git` formula isn't uninstalled to avoid rebuilds if there was a dependent due to be tested in the same job.

In addition to the situation above, the situation is worsened in the event that a git build is cancelled. This doesn't have to be manual - adding another commit to the pull request or force-pushing will trigger a cancellation. If it is cancelled in the middle of cleanup, the brew git install might not be wiped. This issue resulted in `mojave_orka_1` having to be taken offline earlier today as homebrew-test-bot currently cannot reach the point of wiping previous installs without a functional git. It requires manually going in and cleaning it up yourself - something I had hoped to have done by now if I wasn't having issues connecting to the Orka service endpoint.

Here is me brainstorming possible solutions:

* Always directly invoke system git. There's a few possible approaches:
  - Directly use `/usr/bin/git` in homebrew-test-bot.
    * This will not work on systems without the CLT. That's not an issue for our machines but may be for others using this tap.
    * It could somewhere else on Linux like `/usr/local/bin/git`.
  - Have homebrew-test-bot do the above and also search other locations (including Xcode.app) in the path that are not a part of Homebrew:
    * This would just end up as a reimplementation of the git shim so I'm not a fan of this approach of duplicating code.
  - Modify the git shim in brew to have an option or environment variable to alter the search and make brew git a last resort.
    * I suggest not just making this the default to reduce the chance of breakages.
      - Notably, `git-filter-repo` requires a newer git so its tests may fail if we change the default as it may go through the shim.
      - On Linux, the system git situation seems to be hit or miss at times so best to just avoid that.
    * How rigourous would we want this? A simple check for a `git` binary in `HOMEBREW_PREFIX/"bin"` or more advanced checks to see whether this is actually a brew-installed git rather than one installed from another location?
      - The shim is a shell script, so doing a more advanced check is a little more tricky than in Ruby and probably requires symlink checking.
    * Adding an option or environment variable feels a bit like a hack specific to homebrew-test-bot, but maybe there's some legitimate use cases in other scenarios.
    * Nevertheless, it's currently my preferred option on this list I reckon.
* Avoid invoking `git` in `cleanup_after` before the brew git is wiped.
  - This approach might not fix all cases. The wipe only occurs at the very end. What if another formula is tested after git in the same job but said formula invokes `git` as a part of its download & install process?
* git-specific hacks in homebrew-test-bot to uninstall brew git immediately
  - Problematic if a dependent is built in the same job - need to rebuild again.
  - Any hack like this probably won't even cover all edge cases - what if that dependent then uses git to download its sources (which should be after git is reinstalled again)?
* Other options I haven't thought of?

I can do some work on this and send a pull request if you want.

**Comment by SMillerDev** [comment]
I've been been thinking about this too but I don't know anything about the internals of testbot. Would it be possible to always use system git in case of a brewed git test?

**Comment by MikeMcQuaid** [comment]
> * Directly use `/usr/bin/git` in homebrew-test-bot.

I reckon this is the best approach for us 👍 



> I can do some work on this and send a pull request if you want.

That would be great, thanks!

**Comment by Bo98** [comment]
Thinking about it again, a quick fix could be to just do `HOMEBREW_GIT_PATH=/usr/bin/git` as a part of the Jenkins config. Ideally we'd do it before the test-bot code is invoked - to deal with the case that cleanup wasn't performed - since we run `brew update-reset` etc. first, but if you think it's better as a part of the codebase somewhere I can do that.

**Comment by MikeMcQuaid** [comment]
> but if you think it's better as a part of the codebase somewhere I can do that.

Yeh, I think so 👍

**Comment by Bo98** [comment]
Ok, will do.

Not sure if the case of `mojave_orka_1` has happened before so is probably not very common scenario anyway.

**Comment by MikeMcQuaid** [comment]
Yeh and even then it should be repaired by this fix I believe.

**Comment by Bo98** [comment]
Well, what caused `mojave_orka_1` to collapse was a previous build was cancelled between `pcre2` uninstall and cleanup. This meant that a broken brew git was still installed, and git is invoked right from the start for future builds - before `brew test-bot` is even reached - notably when running `brew update-reset` and actually also Jenkin's own git cloning (which is configurable). So while changing `homebrew-test-bot` will fix the much more common case of it simply failing at the end, it probably wouldn't have prevented `mojave_orka_1` breaking.

**Comment by MikeMcQuaid** [comment]
It would have resulted in a broken build but the `brew test-bot` cleanup stuff would be able to successfully run `git` and clean up the broken packages at that point. Arguably `brew test-bot --cleanup` or something could be run before we attempt to run `brew update-reset` or `brew update` but given Jenkins isn't long for this world I'm not sure it's worth it.
