### ISSUE TITLE
Won't work on Linux due to removal of Library/Homebrew/vendor/portable-ruby/

### ISSUE THREAD

**Issue by equal-l2** [Homebrew/homebrew-test-bot#43]
Reffer:https://travis-ci.org/Homebrew/homebrew-science/builds/180950856

CI tests on [Homebrew/homebrew-science](https://github.com/Homebrew/homebrew-science) fails constantly due to the following error in executing `brew test-bot`, on line 770 and 771:

```
==> brew --env
/home/linuxbrew/.linuxbrew/Library/Homebrew/brew.sh: line 353: /home/linuxbrew/.linuxbrew/Library/Homebrew/vendor/portable-ruby/current/bin/ruby: No such file or directory
```

I think this is caused by the following process, from line 761 to 764:

```
git clean -ffdx --exclude=Library/Taps
Removing Library/Homebrew/vendor/portable-ruby/
Removing share/
Removing var/
```
Why `brew` deletes portable-ruby by itself?

**Comment by MikeMcQuaid** [comment]
This does work on Linux: this repository uses Homebrew/brew's Linux support and it works there.. This should be fixed in Linuxbrew and/or the Travis CI configuration.

**Comment by equal-l2** [comment]
Oh sorry, I didn't notice it.
