### ISSUE TITLE
Is there some documentation for indended usage

### ISSUE THREAD

**Issue by PurpleBooth** [Homebrew/homebrew-test-bot#474]
I'm really struggling to work out why brew test-bot is resetting the changes I want to test in a formula. (Note: this works locally but not on Github's actions, which is frustrating.).

```
brew update-reset
brew tap purplebooth/repo
cp formula/formula.rb "$(brew --repo)/Library/Taps/purplebooth/homebrew-repo/Formula/$REPOSITORY_NAME.rb"
brew install "purplebooth/repo/$REPOSITORY_NAME"
brew test-bot \
            --tap=purplebooth/repo \
            "purplebooth/repo/$REPOSITORY_NAME"
brew test-bot \
            --ci-upload \
            --bintray-org="$BINTRAY_ORG" \
            --root-url="$BINTRAY_DL_URL" \
            --tap=purplebooth/repo \
            --git-name="$GITHUB_ACTOR" \
            --git-email="$GITHUB_ACTOR@users.noreply.github.com" \
            --publish \
            "purplebooth/repo/$REPOSITORY_NAME"
```

This ticket isn't about this individual problem, but rather the lack of a resource that tells me the expected workflow for the tool. I assume I can get to the bottom of this, but it'd be really nice if the help page gave some indication of the workflow you expect with the tool.

To clarify:

It's clear from the code that different things happen if environment variables like "UPSTREAM_PULL_REQUEST" are set. So it looks like from the code you're assuming we're not using a CD pipeline, but a pull request flow. How do these environment variables change the behaviour of the tool, depending on if they are or are not set.

**Comment by SMillerDev** [comment]
To make sure that this actually clarifies what you want from it, could you make a pull request adding documentation stating how you _think_ it works. And then the homebrew maintainers that are more knowledgeable can comment and iterate on that with you.

**Comment by PurpleBooth** [comment]
Sure! I'll see if I can put something together. Is just embedded in the repo in a docs folder ok?

**Comment by SMillerDev** [comment]
For now I think that's okay (though other maintainers might disagree)

**Comment by MikeMcQuaid** [comment]
Closing as this isn't a issue per-se but happy to keep discussing here. As mentioned elsewhere: `brew tap-new` is the main input path for `brew test-bot` if you're unfamiliar with it. It's primarily (for now) a tool for our own CI usage that may be useful to others rather than something we actively support.
