### ISSUE TITLE
error: Not a valid ref: refs/remotes/origin/master

### ISSUE THREAD

**Issue by ddelange** [Homebrew/homebrew-test-bot#488]
With a [GH Actions template](https://github.com/ddelange/homebrew-ffmpeg/blob/3272cfac1d9fac578220935cce15dcdf7ef16b42/.github/workflows/main.yml) taken/adapted from the default one coming from `brew tap-new`, several errors occur when running on ubuntu-latest.

Maybe it's a mix up (`set -e` is part of the `macos` script), where the `ubuntu` setup originated [elsewhere](https://github.com/Homebrew/linuxbrew-core/blob/1230c76dbf1e2e6f0bd5ef4cd650189b7db0da48/.github/workflows/tests.yml#L16).

Maybe I'm missing something obvious, or missed the right documentation. Do you have a correct workflow example of testing a 3rd party tap on both macos and ubuntu?

[Logs](https://github.com/ddelange/homebrew-ffmpeg/runs/1041253395#step:4:21)
```
  set -e
  brew update
  HOMEBREW_TAP_DIR="/usr/local/Homebrew/Library/Taps/homebrew-ffmpeg/homebrew-ffmpeg"
  mkdir -p "$HOMEBREW_TAP_DIR"
  rm -rf "$HOMEBREW_TAP_DIR"
  ln -s "$PWD" "$HOMEBREW_TAP_DIR"
  brew test-bot
  shell: /bin/bash -e {0}
  env:
    HOMEBREW_COLOR: 1
/usr/lib/ruby/vendor_ruby/rubygems/defaults/operating_system.rb:10: warning: constant Gem::ConfigMap is deprecated
/usr/lib/ruby/vendor_ruby/rubygems/defaults/operating_system.rb:10: warning: constant Gem::ConfigMap is deprecated
/usr/lib/ruby/vendor_ruby/rubygems/defaults/operating_system.rb:29: warning: constant Gem::ConfigMap is deprecated
/usr/lib/ruby/vendor_ruby/rubygems/defaults/operating_system.rb:30: warning: constant Gem::ConfigMap is deprecated
/usr/lib/ruby/vendor_ruby/rubygems/defaults/operating_system.rb:10: warning: constant Gem::ConfigMap is deprecated
/usr/lib/ruby/vendor_ruby/rubygems/defaults/operating_system.rb:10: warning: constant Gem::ConfigMap is deprecated
/usr/lib/ruby/vendor_ruby/rubygems/defaults/operating_system.rb:29: warning: constant Gem::ConfigMap is deprecated
/usr/lib/ruby/vendor_ruby/rubygems/defaults/operating_system.rb:30: warning: constant Gem::ConfigMap is deprecated
error: Not a valid ref: refs/remotes/origin/master
fatal: ambiguous argument 'refs/remotes/origin/master': unknown revision or path not in the working tree.
Use '--' to separate paths from revisions, like this:
'git <command> [<revision>...] -- [<file>...]'
==> Homebrew is run entirely by unpaid volunteers. Please consider donating:
  https://github.com/Homebrew/brew#donations
Updated 1 tap (ddelange/ffmpeg).
No changes to formulae.
mkdir: cannot create directory ‘/usr/local/Homebrew’: Permission denied
##[error]Process completed with exit code 1.
```

**Comment by MikeMcQuaid** [comment]
> Do you have a correct workflow example of testing a 3rd party tap on both macos and ubuntu?

https://github.com/Homebrew/homebrew-bundle/blob/master/.github/workflows/tests.yml.

This should match what `tap-new` is doing so I'd recommend trying to use that instead. None of your "run test bot" precursors are necessary; they are done by `set-up-homebrew`.
