### ISSUE TITLE
test-bot does not recognize renamed tap

### ISSUE THREAD

**Issue by ddelange** [Homebrew/homebrew-test-bot#498]
Hi,

Going by @dawidd6's [homebrew-tap](https://github.com/dawidd6/homebrew-tap) workflows, I noticed that the command [does not pick](https://github.com/ddelange/brewformulae/runs/1101292745#step:3:5) up my tap, and defaults to Homebrew/core.

Here's the failing yaml:
https://github.com/ddelange/brewformulae/blob/594254e1cbd2c4a906f3308d2633e838fd7f6bcb/.github/workflows/brew-test-bot.yml

Here's an example run of the command correctly picking up the tap it's in:
https://github.com/dawidd6/homebrew-tap/runs/975810574#step:4:7

My hunch is that the command looks for the `homebrew-` prefix in the repo it's in, but doesn't find it on my repo, because it's no longer called https://github.com/ddelange/homebrew-brewformulae (and instead redirects, so no problem for brew when I'd do a `brew install ddelange/brewformulae/yt`. 

Any chance I can trick the test-bot command into picking up my tap, and doing the checks?

**Comment by dawidd6** [comment]
Couldn't you just rename your repo to something `homebrew-` prefixed?

**Comment by ddelange** [comment]
Yes of course that would be fallback, but I actually quite liked the looks of `ddelange/brewformulae`, and having a repo called `ddelange/homebrew-brewformulae` somehow sounds unnecessary.

If it's nothing I can fix by e.g. passing certain command line args (or anything you can think of), feel free to close, as probably not many ppl have taps that don't start with `homebrew-` prefix.

**Comment by dawidd6** [comment]
Did you try passing `--tap` option with proper argument to `brew test-bot`?

**Comment by ddelange** [comment]
Yes, `brew test-bot --tap ${{ github.repository }}` which expands to `ddelange/brewformulae` seems to be ignored

**Comment by MikeMcQuaid** [comment]
Note `brew tap ddelange/brewformulae` only works because it's using the repository redirection from `ddelange/homebrew-brewformulae`.

**Comment by MikeMcQuaid** [comment]
I'd strongly recommend renaming your tap to something with a `homebrew-` prefix.
