### ISSUE TITLE
Failure on brew test-bot perl

### ISSUE THREAD

**Issue by ddelange** [Homebrew/homebrew-test-bot#499]
When running `brew test-bot homebrew-ffmpeg/ffmpeg/ffmpeg`, recursively `perl`'s post install step [fails](https://github.com/homebrew-ffmpeg/homebrew-ffmpeg/pull/49/checks?check_run_id=1097232122#step:3:1268) (ref https://github.com/homebrew-ffmpeg/homebrew-ffmpeg/pull/49), and so tests are failing on the 3rdf party ffmpeg test-bot run on ubuntu ([yaml](https://github.com/homebrew-ffmpeg/homebrew-ffmpeg/blob/dba8eaf0a37d6ed970dc61d602fc5d0ed9a7b336/.github/workflows/main.yml)).

Also beforehand installing perl from source (successfully, https://github.com/homebrew-ffmpeg/homebrew-ffmpeg/pull/48/commits/77e9d7f95a57d437d489e0506b0ce34817effb76) won't hinder brew test-bot to incorporate the failing perl bottle.

As I'm not sure if this a bottling issue (ref https://github.com/Homebrew/linuxbrew-core/issues/4808) that might be re-opened, or a caveat of test-bot, I'm not sure where to raise this issue.

Curious about your advise/ideas @dawidd6 :)

**Comment by MikeMcQuaid** [comment]
Sorry, I can't understand from what you're asking what the issue you're having is.

**Comment by dawidd6** [comment]
It's an issue with perl formula in linuxbrew-core. We'll welcome any PRs fixing it.
