### ISSUE TITLE
testbot fails since a while without a workflow change

### ISSUE THREAD

**Issue by kaoh** [Homebrew/homebrew-test-bot#504]
Since approx. 4 weeks the build check in GitHub does not work anymore. I see always the error:

~~~ 
Error: Invalid usage: Did not find any formulae or commits to test!
Error: Process completed with exit code 1.
~~~ 

Here is the failed build: https://github.com/kaoh/homebrew-globalplatform/runs/1168873594?check_suite_focus=true

I have not changed the GitHub workflow, so it must be an incompatible upstream change.

~~~
name: brew test-bot
on:
  push:
    branches: master
  pull_request: []
jobs:
  test-bot:
    runs-on: macos-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v2
      - name: Run brew test-bot
        run: |
          set -e
          brew update
          HOMEBREW_TAP_DIR="/usr/local/Homebrew/Library/Taps/kaoh/homebrew-globalplatform"
          mkdir -p "$HOMEBREW_TAP_DIR"
          rm -rf "$HOMEBREW_TAP_DIR"
          ln -s "$PWD" "$HOMEBREW_TAP_DIR"
          brew test-bot
~~~

https://github.com/kaoh/homebrew-globalplatform/blob/master/.github/workflows/main.yml

**Comment by MikeMcQuaid** [comment]
https://github.com/Homebrew/brew/blob/dc09aa6d0ca3c89dab2a4d8cb6274d6d77e063e7/Library/Homebrew/dev-cmd/tap-new.rb#L48-L85 is our supported workflow.

**Comment by kaoh** [comment]
Sorry, this does not help me enough. Where is a working example and what has changed since the time it was working? Where are these breaking changes announced? In your referenced link I see:

~~~
            - name: Install Homebrew Bundler RubyGems
              if: steps.cache.outputs.cache-hit != 'true'
              run: brew install-bundler-gems
            - run: brew test-bot --only-cleanup-before
            - run: brew test-bot --only-setup
            - run: brew test-bot --only-tap-syntax
            - run: brew test-bot --only-formulae
              if: github.event_name == 'pull_request'
~~~

Before `brew test-bot` was sufficient, now this seems to be broken. Do I have to run now all these runs to have the same result as before?

**Comment by MikeMcQuaid** [comment]
> Sorry, this does not help me enough.

I'm sorry, we do not provide support for this tooling. 

> Where is a working example and what has changed since the time it was working?

The output of `brew tap-new` or, if you want to see a real-life use-case: pretty much every `homebrew-*` repository in the Homebrew organisation. As for what's changed since it last worked (for you): sorry I have no idea.

> Before `brew test-bot` was sufficient, now this seems to be broken. Do I have to run now all these runs to have the same result as before?

I have no idea what your workflow before was and what you plan for it to be. I cannot justify debugging your individual workflow, sorry.
