### ISSUE TITLE
Standard Brewfile fails brew style RuboCop checks

### ISSUE THREAD

**Issue by danielbayley** [Homebrew/homebrew-test-bot#522]
So I have a [`Brewfile`](https://github.com/danielbayley/homebrew-dotfiles/blob/master/Brewfile) in my _[homebrew-dotfiles](https://github.com/danielbayley/homebrew-dotfiles)_ tap… which is the output from `brew bundle dump --force --describe`. I now also have updated my GitHub Actions CI to make use of `brew test-bot` (based on the `tests.yml` output from `brew tap-new`). However the `brew test-bot --only-tap-syntax` step obviously includes this `Brewfile` when running `brew style` on the whole tap, which results in the following errors:

`Brewfile:1:1: C: Missing frozen string literal comment.` (which is not output by `brew bundle dump`) and `Use underscores(_) as thousands separator and separate every 3 digits with them.` due to the long `id:` integer [output](https://github.com/danielbayley/homebrew-dotfiles/blob/master/Brewfile#L327-L350) from `mas` installed apps.

How can I fix this? Could/should the `brew style` RuboCop checks skip these rules for `Brewfile`s, or could the output from `brew bundle dump` be altered so that `brew test-bot --only-tap-syntax` can pass?

**Comment by reitermarkus** [comment]
I guess we can either fix `brew bundle` to include the `frozen_string_literal` comment in `Brewfile`s or change the `.rubocop.yml` to exclude `Brewfile`.

**Comment by MikeMcQuaid** [comment]
Yes, either seems acceptable to me. Closing this as I don't consider this a test-bot issue but we'd review a PR for this!

**Comment by reitermarkus** [comment]
> Ideally just those 2 rules would be disabled for `Brewfile`s… is that not possible?

Yes.

**Comment by danielbayley** [comment]
Ok, sounds simple enough then. I'll try a [hopefully] quick PR…

@reitermarkus @MikeMcQuaid Am I right in it one of [these](https://github.com/Homebrew/brew/tree/master/Library) `.rubocop*.yml`s?

**Comment by reitermarkus** [comment]
Yes, the plain one, `.rubocop.yml`.

**Comment by danielbayley** [comment]
@reitermarkus @MikeMcQuaid Just passed all checks in #9169 👍
