### ISSUE TITLE
Also test Casks

### ISSUE THREAD

**Issue by danielbayley** [Homebrew/homebrew-test-bot#523]
Currently `test-bot` is set up to only work on formulae, yet seems designed (as output by `tap-new`) to be for Taps in general… So surely it should also check Casks?

See also: https://github.com/Homebrew/discussions/discussions/41#discussioncomment-93844

**Comment by MikeMcQuaid** [comment]
> So surely it should also check Casks?

No. This would be a major undertaking that would require a lot of work on the casks side. It's something we'd consider accepting a PR for (if it were to be used by official cask taps).

**Comment by danielbayley** [comment]
> This would be a major undertaking that would require a lot of work on the casks side.

@MikeMcQuaid Would it be much more complicated than adding the appropriate `cask style`/`audit` checks for [any] files in `Casks/`?

> if it were to be used by official cask taps

That was part of the idea… Those obviously already have their own separate CI currently; would it not be simpler/preferable/more maintainable long-term to for `test-bot` to handle all CI? (with the added benefit of being available for Taps)

**Comment by reitermarkus** [comment]
Currently Cask CI is basically a collection of GitHub Actions so I'd say it would be pretty hard to condense this into a single command. Also not really desirable if you ask me, since having multiple GitHub Actions gives much easier to read output than a single script.

**Comment by MikeMcQuaid** [comment]
I'd rather get more code out of test-bot rather than more code into it. It's a bit of a monstrosity.

**Comment by danielbayley** [comment]
> Currently Cask CI is basically a collection of GitHub Actions so I'd say it would be pretty hard to condense this into a single command. Also not really desirable if you ask me, since having multiple GitHub Actions gives much easier to read output than a single script.

Understandable. @reitermarkus So could there be an official Tap template (as you [mention here](https://github.com/Homebrew/discussions/discussions/41#discussioncomment-93844)) that brings all of those together so that any `tap-new` points to the same CI workflow that will check formulae with `test-bot`, Casks, cmds, and `Brewfile`s using the other existing actions?

> I'd rather get more code out of test-bot rather than more code into it.

Always preferable!

**Comment by reitermarkus** [comment]
Yes, ideally, as I mentioned, `tap-new` would create a tap from a template repository and there would be an action which keeps the configuration in sync with the template repository.
