### ISSUE TITLE
Upload issue with GitHub Releases

### ISSUE THREAD

**Issue by ticky** [Homebrew/homebrew-test-bot#531]
Hi there, I’ve been trying to follow the steps [outlined in this recent blog post](https://brew.sh/2020/11/18/homebrew-tap-with-bottles-uploaded-to-github-releases/) to test and build bottles for some taps I maintain, and I’ve run into a snag.

I’ve managed to adapt the workflows and get those set up, and created a PR which modifies the formulae so that they’re built, but at the point of asking it to publish the bottles and merge it, I’ve run into [this error](https://github.com/ticky/homebrew-utilities/runs/1490208264?check_suite_focus=true#step:4:393):

```
==> Uploading cxmon-2020-07-05T515644Z.x86_64_linux.bottle.tar.gz
/usr/bin/curl --disable --globoff --show-error --user-agent Linuxbrew/2.6.0-51-gedb7496\ \(Linux\;\ x86_64\ Ubuntu\ 18.04.5\ LTS\)\ curl/7.58.0 --header Accept-Language:\ en --retry 3 --location https://uploads.github.com/repos/ticky/homebrew-utilities/releases/34729864/assets\?name=cxmon-2020-07-05T515644Z.x86_64_linux.bottle.tar.gz --header Accept:\ application/vnd.github.v3\+json --write-out '
'\%\{http_code\} --header Accept:\ application/vnd.github.antiope-preview\+json --header Authorization:\ token\ ****** --data-binary @cxmon--2020-07-05T515644Z.x86_64_linux.bottle.tar.gz --header Content-Type:\ application/gzip --dump-header /tmp/github_api_headers20201203-3199-16b571v
Error: Validation Failed: [{"resource"=>"ReleaseAsset", "code"=>"custom", "field"=>"size", "message"=>"size is not included in the list"}]
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/utils/github.rb:289:in `raise_api_error'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/utils/github.rb:234:in `open_api'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/utils/github.rb:506:in `upload_release_asset'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/dev-cmd/pr-upload.rb:124:in `block (2 levels) in pr_upload'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/dev-cmd/pr-upload.rb:120:in `each_value'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/dev-cmd/pr-upload.rb:120:in `block in pr_upload'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/dev-cmd/pr-upload.rb:104:in `each_value'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/dev-cmd/pr-upload.rb:104:in `pr_upload'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/brew.rb:119:in `<main>'
Error: Failure while executing; `/home/linuxbrew/.linuxbrew/bin/brew pr-upload --debug --bintray-org=homebrew` exited with 1.
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/utils.rb:294:in `safe_system'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/dev-cmd/pr-pull.rb:445:in `block (3 levels) in pr_pull'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/vendor/portable-ruby/2.6.3_2/lib/ruby/2.6.0/fileutils.rb:128:in `chdir'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/vendor/portable-ruby/2.6.3_2/lib/ruby/2.6.0/fileutils.rb:128:in `cd'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/dev-cmd/pr-pull.rb:396:in `block (2 levels) in pr_pull'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/vendor/portable-ruby/2.6.3_2/lib/ruby/2.6.0/tmpdir.rb:93:in `mktmpdir'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/dev-cmd/pr-pull.rb:395:in `block in pr_pull'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/dev-cmd/pr-pull.rb:381:in `each'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/dev-cmd/pr-pull.rb:381:in `pr_pull'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/brew.rb:119:in `<main>'
```

Now, this seems to be coming from the GitHub API, and from searching for that error, indicate GitHub is rejecting the asset as too big. However, all of the bottles built in this PR add up to 20 megabytes per platform, so I’m not sure how it could be over the line there.

Unfortunately, while this build _has_ uploaded several bottles, due to this failure it has not committed any of them into the formula files.

I’m hoping you can help with this tooling, as the idea of first-class support for this is really exciting!

**Comment by dawidd6** [comment]
This is most likely a problem with GitHub API as I see other bottles were uploaded successfully in this workflow run you provided the link to. At this point I have no idea what can be done with that on our side.

**Comment by MikeMcQuaid** [comment]
> At this point I have no idea what can be done with that on our side.

Given this and @dawidd6 being the original author, closing, sorry!

**Comment by ticky** [comment]
I seem to be having somewhat better luck touching each Formula separately rather than attempting to do it all at once, though it incurs more overhead and honestly feels like this ought to handle this case better. Is retry behaviour not in the realm of possibility at all?

**Comment by MikeMcQuaid** [comment]
We'd review PRs for either approach 👍🏻

**Comment by ticky** [comment]
Digging into this further, this appears to have occurred because the asset in question was never actually there; the CI configuration (unchanged from the `brew tap-new` output) somehow created the bottle’s json file, but not the actual bottle. The presence of the json appears to make the `pr-pull` expect it to exist.

<img width="361" alt="image" src="https://user-images.githubusercontent.com/282113/101088310-58f11e80-3568-11eb-9d5a-9eb50f6605eb.png">

You can see [here](https://github.com/ticky/homebrew-utilities/runs/1490027510#step:9:6) that there is an uneven number of assets uploaded from the Linux build. Is that expected given the [output from the build of that bottle](https://github.com/ticky/homebrew-utilities/runs/1490027510#step:8:37)? I think it’s missing a dependency declaration on Linux, but there’s nothing indicating this should’ve failed to build otherwise to my eye.

Should `pr-pull` be tolerant of this flavour of failure, or should `test-bot` be emitting a clearer error and/or cleaning up after this flavour of error?

**Comment by MikeMcQuaid** [comment]
> Should `pr-pull` be tolerant of this flavour of failure, or should `test-bot` be emitting a clearer error and/or cleaning up after this flavour of error?

I'd say both!
