### ISSUE TITLE
Should check for unlinked dependencies of all dependents, not just named formulae

### ISSUE THREAD

**Issue by scpeters** [Homebrew/homebrew-test-bot#544]
While investigating CI failures in https://github.com/Homebrew/homebrew-core/pull/67615 (applying an upstream patch to boost), I noticed that `brew test pcl` failed for all architectures, even though it had passed very recently in https://github.com/Homebrew/homebrew-core/pull/66792. The tests in https://github.com/Homebrew/homebrew-core/pull/67615 failed to find `eigen` when running cmake to configure some sample code that links against `pcl`. Searching earlier in the console log, I noticed `brew unlink eigen` just before `freeling` was tested. Looking at the console logs from https://github.com/Homebrew/homebrew-core/pull/66792, I noticed the same call to `brew unlink eigen` just before `freeling`, but there was also a call to `brew link eigen` just before `pcl` was handled. The difference between those two pull requests is that `pcl` received a revision bump in the earlier one, and there is logic in [setup_formulae_deps_instances() in lib/tests/formulae.rb](https://github.com/Homebrew/homebrew-test-bot/blob/c84e3cc71132ba81a7375c44a48f6b1da6dee266/lib/tests/formulae.rb#L248-L270) that calls `brew link` on unlinked dependencies for any formulae to be built. I believe this logic should be added to link dependencies for any dependents that are installed, not just the explicitly named formulae to be tested.

**Comment by MikeMcQuaid** [comment]
> The difference between those two pull requests is that `pcl` received a revision bump in the earlier one, and there is logic in [setup_formulae_deps_instances() in lib/tests/formulae.rb](https://github.com/Homebrew/homebrew-test-bot/blob/c84e3cc71132ba81a7375c44a48f6b1da6dee266/lib/tests/formulae.rb#L248-L270) that calls `brew link` on unlinked dependencies for any formulae to be built. I believe this logic should be added to link dependencies for any dependents that are installed, not just the explicitly named formulae to be tested.

Makes sense to me @scpeters! Could you open a PR?

**Comment by scpeters** [comment]
> > The difference between those two pull requests is that `pcl` received a revision bump in the earlier one, and there is logic in [setup_formulae_deps_instances() in lib/tests/formulae.rb](https://github.com/Homebrew/homebrew-test-bot/blob/c84e3cc71132ba81a7375c44a48f6b1da6dee266/lib/tests/formulae.rb#L248-L270) that calls `brew link` on unlinked dependencies for any formulae to be built. I believe this logic should be added to link dependencies for any dependents that are installed, not just the explicitly named formulae to be tested.
> 
> Makes sense to me @scpeters! Could you open a PR?

I'll work up the courage and give it a shot :sweat_smile:

**Comment by scpeters** [comment]
potential fix in #659
