### ISSUE TITLE
test-bot shouldn't skip new formulae on ARM CI

### ISSUE THREAD

**Issue by carlocab** [Homebrew/homebrew-test-bot#562]
This follows from https://github.com/Homebrew/homebrew-core/pull/69708.

Currently, test-bot does not attempt to build or test formulae using (I think) the following logic:

https://github.com/Homebrew/homebrew-test-bot/blob/86c53a3edab345504ebd2eb863ce87419ed837de/lib/tests/formulae.rb#L578-L585

This requires adding the `CI-force-arm` label so that test-bot will attempt an ARM build for new formulae. We shouldn't need to do this, and it would be good if `test-bot` recognises that a formula is new and attempt a build even if the `CI-force-arm` label is not set.

I'm still mulling over the right approach, so suggestions here would be appreciated.

**Comment by carlocab** [comment]
Here's one idea:

```diff
diff --git a/lib/tests/formulae.rb b/lib/tests/formulae.rb
index a9ec56b..f4df21a 100644
--- a/lib/tests/formulae.rb
+++ b/lib/tests/formulae.rb
@@ -576,7 +576,7 @@ module Homebrew
         end
 
         if Hardware::CPU.arm? &&
-           ENV["HOMEBREW_REQUIRE_BOTTLED_ARM"] &&
+           (ENV["HOMEBREW_REQUIRE_BOTTLED_ARM"] || ENV["HOMEBREW_NEW_FORMULA"]) &&
            !formula.bottled? &&
            !formula.bottle_unneeded?
           opoo "#{formula.full_name} has not yet been bottled on ARM!"
```

But we'd need the `HOMEBREW_NEW_FORMULA` environment variable to be set for new formulae for this to work. Presumably, this can be done in the same way `HOMEBREW_REQUIRE_BOTTLED_ARM` is set.

Thoughts, @MikeMcQuaid?

**Comment by bayandin** [comment]
> But we'd need the `HOMEBREW_NEW_FORMULA` environment variable to be set for new formulae for this to work. Presumably, this can be done in the same way `HOMEBREW_REQUIRE_BOTTLED_ARM` is set.

Can we use `new_formula = @added_formulae.include?(formula_name)` (from line 598, we'll need to move it up):

https://github.com/Homebrew/homebrew-test-bot/blob/cfed23d743398e3f667918d0a50a0f5f667c327e/lib/tests/formulae.rb#L578-L604

**Comment by carlocab** [comment]
Great suggestion; I was looking for where `test-bot` figured out whether a formula was new. I'll open a PR for this.
