### ISSUE TITLE
Add action to remove `awaiting user reply`

### ISSUE THREAD

**Issue by georgettica** [Homebrew/homebrew-test-bot#581]
As a user I created a issue, and got the label `awaiting user reply` after a response

I don't have permission to remove the label nor an automated command to remove it.

### Steps taken
- `BrewTestBot` or it's github repo doesn't hold any github action / README related to an action like so
- previous issues in https://github.com/Homebrew/homebrew-cask/ do not have this label / a way to communicate to the bot
- https://docs.brew.sh/ doesn't refer to this in the docs

### Related to
https://github.com/Homebrew/homebrew-cask/issues/101129

**Comment by MikeMcQuaid** [comment]
This label is set/unset by maintainers manually. We don't want to automate this at this time.
