### ISSUE TITLE
--skip-recursive-dependents flag seems broken

### ISSUE THREAD

**Issue by iMichka** [Homebrew/homebrew-test-bot#599]
I noticed recently that using `--skip-recursive-dependents` flag on Linux CI (to reduce build time) does not work anymore.

Right now the full list of dependants is being tested. I checked locally and the `--recursive` flags is removed from the `brew uses` call. But nevertheless, the full list of dependants is being tested. So something else is going on.

**Comment by MikeMcQuaid** [comment]
There's not enough here to go on I'm afraid. As you note: `--recursive` isn't being added and `f.deps` is being used instead of `f.recursive_dependencies`. If you can provide a reproducible test case we can look into this more.
