### ISSUE TITLE
Linkage tests are passing when they should fail

### ISSUE THREAD

**Issue by carlocab** [Homebrew/homebrew-test-bot#611]
`clazy` passed CI in Homebrew/homebrew-core#77005, but then failed the linkage check in [this CI run](https://github.com/Homebrew/homebrew-core/actions/runs/848283367) (Homebrew/homebrew-core#77434).

It was then given a `revision` bump to rebuild it, and I thought that shook off the linkage (as CI passed after the `revision` bump), but the new bottle still shows broken linkage:
```
❯ brew linkage clazy
System libraries:
  /usr/lib/libSystem.B.dylib
  /usr/lib/libncurses.5.4.dylib
  /usr/lib/libxml2.2.dylib
  /usr/lib/libz.1.dylib
Variable-referenced libraries:
  @rpath/ClazyPlugin.dylib
Broken dependencies:
  /usr/local/opt/llvm@11/lib/libc++.1.dylib (llvm@11)
Dependencies with no linkage:
  qt
```

This seems to be the step that causes it: https://github.com/Homebrew/homebrew-core/runs/2597888223#step:7:768

**Comment by MikeMcQuaid** [comment]
@carlocab Can you reproduce this locally? This feels like it may be a `brew linkage` bug rather than `test-bot` no?

**Comment by carlocab** [comment]
`brew linkage --test clazy` fails for locally. I think the reason why it doesn't fail on CI is that `test-bot` does not uninstall `llvm@11` at any point before running `brew linkage --test`.

At least, that was my theory when I said

>This seems to be the step that causes it: https://github.com/Homebrew/homebrew-core/runs/2597888223#step:7:768

I should've explained that more clearly; sorry. `brew linkage --test clazy` does not fail for me when I have `llvm@11` installed.

My view was that `test-bot` should be uninstalling `llvm@11` here, but I suppose one could also argue that `brew linkage --test` shouldn't succeed when you have undeclared dependencies with linkage installed.

**Comment by MikeMcQuaid** [comment]
https://github.com/Homebrew/homebrew-test-bot/blob/6e16d91a51060bba094a8ec967312665e5addda5/lib/tests/formulae.rb#L472-L475 is probably the relevant code here. It's balance between correctness and timeliness. It maybe warrants being tweaked so it keeps the bottle around and reinstalls from that when needed.

**Comment by MikeMcQuaid** [comment]
@carlocab Is this still a problem?

**Comment by carlocab** [comment]
It hasn't come up since, but I don't think it's been fixed. We can probably close this out since it's not a huge problem -- and we should get at least a warning for this with `brew linkage --test --strict`.

**Comment by MikeMcQuaid** [comment]
Thanks @carlocab!
