### ISSUE TITLE
Error during `brew test-bot --only-formulae` step on tap CI

### ISSUE THREAD

**Issue by ticky** [Homebrew/homebrew-test-bot#646]
Hi there,

I have a handful of taps I maintain, and I've been using the Homebrew-ordained CI solution created by `brew tap-new`.

In the past few days, I've had two unrelated formula on separate taps fail to build in the Linux portion of this CI run, with no clear way of fixing or debugging further, both during the `brew test-bot --only-formulae` step:

```
==> brew uninstall --force ticky/dreamcast/gditools3
Error: No such file or directory @ rb_file_s_link - (./gditools3--3.0.1.x86_64_linux.bottle.tar.gz, /home/runner/.cache/Homebrew/downloads/7b2a5e8cc188a648502bb6ef03004a5db2c384852c167ee93d9ca8a02a10a220--gditools3-3.0.1.x86_64_linux.bottle.tar.gz)
Error: Process completed with exit code 1.
```

[GitHub Actions run](https://github.com/ticky/homebrew-dreamcast/pull/9/checks?check_run_id=3011506550) (Will likely expire soon) • [Full run log archive](https://github.com/Homebrew/homebrew-test-bot/files/6798655/logs_42.zip)

```
==> brew uninstall --force ticky/playstation/paladin
Error: No such file or directory @ rb_file_s_link - (./paladin--1.3_1.x86_64_linux.bottle.2.tar.gz, /home/runner/.cache/Homebrew/downloads/a48a404125187f63ff6bb4915949b8ae21508e7ef8aa8b2090fa05ba519e3770--paladin-1.3_1.x86_64_linux.bottle.2.tar.gz)
Error: Process completed with exit code 1.
```

[GitHub Actions run](https://github.com/ticky/homebrew-playstation/pull/47/checks?check_run_id=3043187194) • [Full run log archive](https://github.com/Homebrew/homebrew-test-bot/files/6798656/logs_73.zip)

There's no obvious connection between these two formulae, and they appear to fail in the same way. There are also no other errors or warnings in the output that I can see which would suggest what's gone wrong here. In the case of the `gditools3` run, this occurred repeatedly under the same conditions.

What's the best way for me to help debug this issue and get things working?

Thanks!

**Comment by dawidd6** [comment]
@iMichka I think you saw an error like this. Did you resolve it?

**Comment by iMichka** [comment]
Yes here: https://github.com/Homebrew/linuxbrew-core/pull/23778

**Comment by MikeMcQuaid** [comment]
@ticky @iMichka I think this is now fixed. Can you attempt to reproduce?

**Comment by iMichka** [comment]
Yes it fixed the issue for me. Thanks!

**Comment by MikeMcQuaid** [comment]
@iMichka @ticky you're both very welcome (and lovely people)!
