### ISSUE TITLE
Annotations and ignore logic not working on Linux

### ISSUE THREAD

**Issue by carlocab** [Homebrew/homebrew-test-bot#712]
For some reason I haven't yet worked out, neither annotations or the ignoring of build/linkage/test failures for unbottled formulae isn't working on Linux.

As best I can tell, the Linux runner seems to exit with an error immediately upon encountering one around here:

https://github.com/Homebrew/homebrew-test-bot/blob/96edbe66a23e103a54187e671e97daea8e615281/lib/step.rb#L104-L107

The ignore logic and annotations come after that, so this would explain why neither is working. I don't know why this is happening specifically on Linux, though.

For examples of this behaviour: Homebrew/homebrew-core#89550 (annotations and ignore), Homebrew/homebrew-core#89042 (annotations and ignore), Homebrew/homebrew-core#89445 (annotations only)

We don't have this problem on macOS. See Homebrew/homebrew-core#89518.

**Comment by MikeMcQuaid** [comment]
No idea here. I wonder if it's something else about the environment rather than the OS i.e. the Linux runner/GitHub Actions runner has some environment variables set that are interfering?

**Comment by carlocab** [comment]
Yea, I'm pretty stumped as well. However, I think my hypothesis about what's going on is correct, judging from what's happening on the Linux runner in this PR: Homebrew/homebrew-core#89567

It has a whole bunch of formulae to test, but it tests `bison` first. The test fails and `test-bot` exits. What it should be doing is logging the failure and moving on to test other formulae.

**Comment by carlocab** [comment]
CC @Homebrew/brew for ideas.

**Comment by Bo98** [comment]
This is your problem:

> Error: No such file or directory @ realpath_rec - /home/runner

**Comment by Bo98** [comment]
This is because of https://github.com/Homebrew/homebrew-core/blob/master/.github/workflows/tests.yml#L182-L190. We would need to change `GITHUB_WORKSPACE` going into this.

I can fix this but I wonder if we can just make it use GitHub's container system somehow (where it'll work out of the box). @dawidd6 I assume you've tried that already and the answer is it doesn't work? Does setting `container` to a blank value on macOS error?

**Comment by carlocab** [comment]
> This is your problem:
> 
> > Error: No such file or directory @ realpath_rec - /home/runner
> 
> Probably from:
> 
> https://github.com/Homebrew/brew/blob/07f14c32e9996196661bdc20830f48797079c463/Library/Homebrew/utils/github/actions.rb#L29

I suspected that too, but IIRC I've seen that error on CI runs well before I started using `GitHub::Actions::Annotation`.

**Comment by Bo98** [comment]
> I suspected that too, but IIRC I've seen that error on CI runs well before I started using `GitHub::Actions::Annotation`.

I'll need to see an example run of this to tell. I've not seen that error until recently and `GITHUB_WORKSPACE` being set to a directory that won't exist in the Docker container makes sense as a cause.

**Comment by dawidd6** [comment]
> Does setting container to a blank value on macOS error?

Yep

**Comment by Bo98** [comment]
> 
> 
> > Does setting container to a blank value on macOS error?
> 
> Yep

This works for me: https://github.com/Bo98/workflow-test/blob/main/.github/workflows/test.yml

**Comment by dawidd6** [comment]
Interesting. Looks like it was changed a year ago:
https://github.com/actions/runner/issues/265

So I guess we can drop a lot of code in our workflows now.

**Comment by carlocab** [comment]
> I'll need to see an example run of this to tell.

Here's an example: https://github.com/Homebrew/homebrew-core/runs/4120630533?check_suite_focus=true#step:7:33

The `ENOENT` seems to happen on an audit failure, which probably means that this is triggered by the annotations code.

On the other hand, it also didn't kill the `test-bot` run, unlike what's happening now.

**Comment by carlocab** [comment]
We'll want to remove

https://github.com/Homebrew/homebrew-test-bot/blob/7e3c529bd62f6bffd1297ebec51b915b208a6351/lib/step.rb#L79-L81

when this is sorted.
