### ISSUE TITLE
Option to skip building unbottled dependents from source

### ISSUE THREAD

**Issue by scpeters** [Homebrew/homebrew-test-bot#731]
I think behavior has changed recently so that unbottled dependents are now built from source instead of being skipped. Is there an option to skip building unbottled dependents to speed up test-bot runs?

**Comment by carlocab** [comment]
Not currently, but adding one seems reasonable.

**Comment by carlocab** [comment]
#736 should restore the old behaviour that unbottled dependents are built from source only when requested with `--build-dependents-from-source`.

**Comment by scpeters** [comment]
thanks @carlocab!
