### ISSUE TITLE
Build bottles for arm64

### ISSUE THREAD

**Issue by ValentinTrinque** [Homebrew/homebrew-test-bot#779]
I am trying to find a way to build arm64 bottles on a tap, using this utility, but I couldn't find out how. I had a look to the homebrew-core repository to find out how it's doing it, but got lost. 

I tried to keep it simple.

My formula is targeting a golang project, so I can cross-compile by setting the GOARCH env var. I assume the project is ccorrectly compiled for arm64, at this point. However, the default file name of the bottle, when creating it, resolves on the underlaying CPU architecture (x86-64). 

Is there a way to make brew test-bot resolve to arm64 during the bottling ? 

Is this possible to reproduce what homebrew-core is doing to auto create the arm64 bottles ? 

Supporting this out of the box could be nice as well.

**Comment by MikeMcQuaid** [comment]
I'm afraid you'll need to figure this out yourself or take it to Homebrew/discussions.
