### ISSUE TITLE
max number of concurrent jobs

### ISSUE THREAD

**Issue by ipatch** [Homebrew/homebrew-test-bot#801]
does test-bot support

https://docs.github.com/en/actions/using-jobs/using-a-matrix-for-your-jobs#defining-the-maximum-number-of-concurrent-jobs

im using three virtual machines for three self hosted runners for the homebrew-freecad tap, and i'd like to limit the workflow to one concurrent job at a time as all three of the runners are running on the same physical computer so does not make sense to run three concurrent jobs at the same time.

i attempted to add the below line to the `tests.yml` file, but after adding that line, it seemed none of the runners would pick up a job 🤷‍♂️

https://github.com/FreeCAD/homebrew-freecad/blob/2ee3e4571000d24c9749ca9969d5906c326c4c6b/.github/workflows/tests.yml#L18

im not sure if this a limitation of test-bot or i'm just misconfiguring github actions for the homebrew-freecad tap.

**Comment by MikeMcQuaid** [comment]
Sorry, this is very specific to GitHub Actions rather than test-bot. I'm afraid I don't know the answer, GitHub support may be more help here.
