### ISSUE TITLE
Tap CI failing on `brew test-bot --only-formulae` on Linux

### ISSUE THREAD

**Issue by figi44** [Homebrew/homebrew-test-bot#946]
Hi, I'm seeing this error in my tap GitHub Actions CI (generated by `tap-new`). It happens only on Ubuntu runner, MacOS runs OK.

```
==> brew test --verbose ecmwf/ecmwf/ecbuild
==> FAILED
Full test ecmwf/ecmwf/ecbuild output
  /home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/vendor/bundle/ruby/2.6.0/bin/bundle clean
  Error: No available formula with the name "cmake".
```
[Run logs](https://github.com/ecmwf/homebrew-ecmwf/actions/runs/5277187233/jobs/9544881270#step:8:47)

Why can't it find the cmake formula and how can I make it test and build on Ubuntu?

Thanks a lot!

**Comment by carlocab** [comment]
Yes, we've had reports of this previously. A workaround is to do
```yaml
env:
  HOMEBREW_NO_INSTALL_FROM_API: 1
```
in your workflow. You may also need this in your workflow in the default branch for `pr-pull` to work.

But we really should fix this properly.

**Comment by MikeMcQuaid** [comment]
@carlocab should we add this to `tap-new` output for now?

**Comment by figi44** [comment]
Thanks for your help, I also realized that cmake was specified as build dependency, but it is also required during runtime.

**Comment by carlocab** [comment]
@MikeMcQuaid a nicer fix might be to handle this in `setup-homebrew` until this problem is fixed so that users don't need to regenerate workflows from `tap-new` in order to benefit from avoiding a Homebrew/core clone.

**Comment by MikeMcQuaid** [comment]
@carlocab Yeh, that would work for me. Would be easier for us to remove when no longer needed, too.

**Comment by Bo98** [comment]
Sorry didn't see this but I think I fixed this months ago. Please try without `HOMEBREW_NO_INSTALL_FROM_API` - you'll probably see improved performance on Linux.
