### ISSUE TITLE
gpsim 0.32.0 bottle issue

### ISSUE THREAD

**Issue by chenrui333** [Homebrew/homebrew-test-bot#979]
👋 the gpsim bottles were built successfully, but failed with `gpsim --version` test on CI.

See this action run, https://github.com/Homebrew/homebrew-core/actions/runs/6746638476/job/18340993658

relates to:
- https://github.com/Homebrew/homebrew-core/pull/153209

cc @Bo98 🙏

**Comment by MikeMcQuaid** [comment]
@chenrui333 What is the question or action item here?

**Comment by Bo98** [comment]
In terms of the test failing: I'm not sure why - but that's not a test-bot issue.

In terms of the bottles not being built in https://github.com/Homebrew/homebrew-core/pull/153209 but CI being green: that's correct behaviour as the bottles were already not there.

See the diff at https://github.com/Homebrew/homebrew-core/commit/3b76c68cb4155711c077f4e74616f80ee08cb01d.

Looking back at the commit history, we've _never_ been able to produce a bottle on arm64_monterey and arm64_ventura for this formula: https://github.com/Homebrew/homebrew-core/commit/0543539c33132c1304274f2562e5c8403ef4a0d2 and https://github.com/Homebrew/homebrew-core/commit/aabbd04eabe900bbd005102eb589b3592b2ce5da. It seems we had issues on x86_64 Ventura as well.

I'll put it on the list to investigate, but I will close this here as it's not a test-bot bug.

**Comment by chenrui333** [comment]
> In terms of the test failing: I'm not sure why - but that's not a test-bot issue. Maybe it's crashing - I would need to reproduce it locally to find out.

I cannot reproduce the issue in my local.

**Comment by chenrui333** [comment]
> @chenrui333 What is the question or action item here?

there is a slack thread, and I just follow the comments and create an issue in here.

**Comment by chenrui333** [comment]
> > In terms of the test failing: I'm not sure why - but that's not a test-bot issue. Maybe it's crashing - I would need to reproduce it locally to find out.
> 
> I cannot reproduce the issue in my local.

Let me dump the ventura arm build logs, if that is helpful
