### ISSUE TITLE
Errors resulting from `--new-formula` deprecation

### ISSUE THREAD

**Issue by neil176** [Homebrew/homebrew-test-bot#991]
I'm seeing errors in my CI pipeline due to deprecation i believe in this PR: https://github.com/Homebrew/brew/pull/16306

```
Error: Calling the `--new-formula` switch is deprecated! Use --new instead
```

Should this be updated to use the new switch or was the deprecation in the other repo premature?

**Comment by neil176** [comment]
Thanks for the quick fix!

**Comment by MikeMcQuaid** [comment]
@neil176 You're welcome!
